
**Descrição de colunas:**
- `Transaction ID:` Número identificador para cada transação.
- `Costomer ID:` Número identificador para cada cliente.
- `Transaction Amount:` Valor da compra. 
- `Transaction Date:` Data e hora da compra. 
- `Payment Method:` Método de pagamento (cartão de crédito, paypal, transferência bancária)
- `Product Category:` Categoria do produto. 
- `Quantity:` Quantia de produtos adquiridos. 
- `Costomer Age:` Idade do cliente.
- `Customer Location:` Endereço do cliente.
- `Device Used:` Dispositivo utilizado para realizar a compra (Tablet, celular, computador)
- `IP Address:` Endereço de IP do dispositivo usado para realizar a compra. 
- `Shipping Address:` Endereço de entrega da compra. 
- `Billing Address:` Endereço de cobrança ou envio da fatura do cartão. 
- `Is Fraudulent:` Indicador binário de se a transação é fraudulenta (1 para fraudulenta, 0 para legítima).
- `Account Age Days:` Há quantos dias a conta foi criada. 
- `Transaction Hour:` Hora do dia em que a compra foi feita. 

_________________________________________________________________________________________________

# **Imports**

In [10]:
import pandas as pd 
import matplotlib as plt

# **Criação do Dataframe**

In [11]:
df_dados = pd.read_csv('Fraudulent_E-Commerce_Transaction_Data.csv')
df_dados

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,15d2e414-8735-46fc-9e02-80b472b2580f,d1b87f62-51b2-493b-ad6a-77e0fe13e785,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5
1,0bfee1a0-6d5e-40da-a446-d04e73b1b177,37de64d5-e901-4a56-9ea0-af0c24c069cf,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,East Timothy,desktop,208.106.249.121,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8
2,e588eef4-b754-468e-9d90-d0e0abfc1af0,1bac88d6-4b22-409a-a06b-425119c57225,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20
4,074a76de-fe2d-443e-a00c-f044cdb68e21,45071bc5-9588-43ea-8093-023caec8ea1c,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,South Nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472947,c8604004-2f4c-42ce-a1c4-cd2bebca79bb,f8a534ad-0458-465e-a85b-3ad2cdf391bc,208.48,2024-01-12 23:39:55,PayPal,health & beauty,2,29,North Laurafort,desktop,27.245.104.92,USNV Griffin\nFPO AA 52700,USNV Griffin\nFPO AA 52700,0,149,23
1472948,fff0df19-fd4a-42a5-bc42-64bb7b02edb0,f2ef2239-d9b9-40d0-9993-4b8f305d5a7b,231.57,2024-03-27 04:31:45,credit card,clothing,2,32,Burnsville,tablet,203.54.50.163,"478 John Square Apt. 235\nMillerhaven, GA 68797","478 John Square Apt. 235\nMillerhaven, GA 68797",0,132,4
1472949,9e79012f-e00b-47d1-8700-0c302db20d3e,fa5b9a25-9606-478a-8abe-ef20bbb3980f,101.80,2024-01-31 23:51:42,bank transfer,electronics,4,36,Garciafort,mobile,51.241.30.149,"351 Frazier Radial Apt. 989\nPort Charles, OH ...","182 House Island Suite 198\nEast Scott, FM 84301",0,98,23
1472950,917066b1-4dfb-4472-b3f0-292663c45d21,04524272-e14f-460b-bc70-5316bd28463d,61.80,2024-01-12 16:21:32,bank transfer,electronics,5,34,Lake Josephberg,desktop,210.67.203.4,"27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...","27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...",0,191,16
1472951,d1a811a2-6015-47fa-95e5-0a5282755932,637d5ed1-a4af-4234-a1d9-a3791b6f1bb6,376.44,2024-02-19 18:57:20,bank transfer,clothing,5,34,Fullermouth,desktop,107.116.208.218,Unit 0520 Box 5911\nDPO AE 75554,Unit 0520 Box 5911\nDPO AE 75554,0,274,18

## **Análise Exploratória**

In [12]:
#Retorna o nome de cada coluna da tabela
df_dados.columns

Index(['Transaction ID', 'Customer ID', 'Transaction Amount',
       'Transaction Date', 'Payment Method', 'Product Category', 'Quantity',
       'Customer Age', 'Customer Location', 'Device Used', 'IP Address',
       'Shipping Address', 'Billing Address', 'Is Fraudulent',
       'Account Age Days', 'Transaction Hour'],
      dtype='object')

In [13]:
df_dados.describe()

,Transaction Amount,Quantity,Customer Age,Is Fraudulent,Account Age Days,Transaction Hour
count,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06,1.472952e+06
mean,2.267683e+02,3.000230e+00,3.451208e+01,5.012926e-02,1.796464e+02,1.128696e+01
std,2.703951e+02,1.414736e+00,1.000313e+01,2.182117e-01,1.068642e+02,6.975995e+00
min,1.000000e+01,1.000000e+00,-1.600000e+01,0.000000e+00,1.000000e+00,0.000000e+00
25%,6.861000e+01,2.000000e+00,2.800000e+01,0.000000e+00,8.600000e+01,5.000000e+00
50%,1.517600e+02,3.000000e+00,3.500000e+01,0.000000e+00,1.790000e+02,1.100000e+01
75%,2.960500e+02,4.000000e+00,4.100000e+01,0.000000e+00,2.720000e+02,1.700000e+01
max,1.270175e+04,5.000000e+00,8.600000e+01,1.000000e+00,3.650000e+02,2.300000e+01

In [14]:
df_dados.head(10)

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,15d2e414-8735-46fc-9e02-80b472b2580f,d1b87f62-51b2-493b-ad6a-77e0fe13e785,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5
1,0bfee1a0-6d5e-40da-a446-d04e73b1b177,37de64d5-e901-4a56-9ea0-af0c24c069cf,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,East Timothy,desktop,208.106.249.121,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8
2,e588eef4-b754-468e-9d90-d0e0abfc1af0,1bac88d6-4b22-409a-a06b-425119c57225,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3
3,4de46e52-60c3-49d9-be39-636681009789,2357c76e-9253-4ceb-b44e-ef4b71cb7d4d,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20
4,074a76de-fe2d-443e-a00c-f044cdb68e21,45071bc5-9588-43ea-8093-023caec8ea1c,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,South Nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5
5,4e707452-7c8a-4cbd-b0c1-2aeaa35c5e88,29616b04-2d5c-4729-9c9d-8d71a6ad9dc1,166.41,2024-01-30 10:55:14,bank transfer,toys & games,2,34,Herreramouth,tablet,202.237.29.55,"5699 Brittany Villages Suite 903\nLake Tim, MD...","120 Kristi Dale\nPort Meganshire, GU 03060",0,38,10
6,7ed952fe-8ae1-4f11-8cc5-6607060240d8,fe21ae29-ba4c-424f-9d55-0095539c09fa,92.88,2024-02-04 19:59:10,PayPal,toys & games,2,14,Ramosfort,tablet,13.45.27.192,"727 Gibson Islands Apt. 279\nNew Davidbury, ME...","727 Gibson Islands Apt. 279\nNew Davidbury, ME...",0,119,19
7,0b2fb5aa-7171-472f-8269-371094608a07,024257c3-5671-4de8-a33c-98fc5cbe6f92,318.14,2024-02-20 13:30:29,credit card,health & beauty,4,42,Port Emily,desktop,131.141.230.185,"3914 Davis Union\nBrownchester, IN 07744","3914 Davis Union\nBrownchester, IN 07744",0,251,13
8,1f52366c-7f40-4397-885f-3856b6e6531c,f17640ca-49da-45d1-8461-c2a1cf9c1b61,47.92,2024-03-03 19:44:00,bank transfer,home & garden,4,38,Carneyfurt,desktop,210.148.17.240,"47893 Maldonado Stream Suite 443\nBrownshire, ...","47893 Maldonado Stream Suite 443\nBrownshire, ...",0,190,19
9,3f10dfde-9c4c-4085-9872-4f6b39502ffb,aab93e75-582f-4455-80b4-1fb35733a47c,121.78,2024-01-16 21:19:39,bank transfer,health & beauty,4,39,Brockburgh,mobile,174.32.252.238,"2334 Briana Centers Suite 576\nArchershire, NM...","2334 Briana Centers Suite 576\nArchershire, NM...",0,343,21

In [15]:
#Verificando os tipos de dados da base
df_dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1472952 entries, 0 to 1472951
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Transaction ID      1472952 non-null  object
 1   Customer ID         1472952 non-null  object
 2   Transaction Amount  1472952 non-null  float64
 3   Transaction Date    1472952 non-null  object
 4   Payment Method      1472952 non-null  object
 5   Product Category    1472952 non-null  object
 6   Quantity            1472952 non-null  int64
 7   Customer Age        1472952 non-null  int64
 8   Customer Location   1472952 non-null  object
 9   Device Used         1472952 non-null  object
 10  IP Address          1472952 non-null  object
 11  Shipping Address    1472952 non-null  object
 12  Billing Address     1472952 non-null  object
 13  Is Fraudulent       1472952 non-null  int64
 14  Account Age Days    1472952 non-null  int64
 15  Transaction Hour    1472952 non-null  int64
dtypes: float64(1), int64(5), object(10)
memory usage: 179.8+ MB

In [16]:
#Verificando se há valores nulos na base de dados
df_dados.isnull().sum()

Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64

In [17]:
#Excluindo colunas irrelevantes na análise
df_dados = df_dados.drop(['Transaction ID', 'Customer ID'], axis=1)

In [18]:
#Exibição da nova tabela com as alterações feitas
df_dados

,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,58.09,2024-02-20 05:58:41,bank transfer,electronics,1,17,Amandaborough,tablet,212.195.49.198,Unit 8934 Box 0058\nDPO AA 05437,Unit 8934 Box 0058\nDPO AA 05437,0,30,5
1,389.96,2024-02-25 08:09:45,debit card,electronics,2,40,East Timothy,desktop,208.106.249.121,"634 May Keys\nPort Cherylview, NV 75063","634 May Keys\nPort Cherylview, NV 75063",0,72,8
2,134.19,2024-03-18 03:42:55,PayPal,home & garden,2,22,Davismouth,tablet,76.63.88.212,"16282 Dana Falls Suite 790\nRothhaven, IL 15564","16282 Dana Falls Suite 790\nRothhaven, IL 15564",0,63,3
3,226.17,2024-03-16 20:41:31,bank transfer,clothing,5,31,Lynnberg,desktop,207.208.171.73,"828 Strong Loaf Apt. 646\nNew Joshua, UT 84798","828 Strong Loaf Apt. 646\nNew Joshua, UT 84798",0,124,20
4,121.53,2024-01-15 05:08:17,bank transfer,clothing,2,51,South Nicole,tablet,190.172.14.169,"29799 Jason Hills Apt. 439\nWest Richardtown, ...","29799 Jason Hills Apt. 439\nWest Richardtown, ...",0,158,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472947,208.48,2024-01-12 23:39:55,PayPal,health & beauty,2,29,North Laurafort,desktop,27.245.104.92,USNV Griffin\nFPO AA 52700,USNV Griffin\nFPO AA 52700,0,149,23
1472948,231.57,2024-03-27 04:31:45,credit card,clothing,2,32,Burnsville,tablet,203.54.50.163,"478 John Square Apt. 235\nMillerhaven, GA 68797","478 John Square Apt. 235\nMillerhaven, GA 68797",0,132,4
1472949,101.80,2024-01-31 23:51:42,bank transfer,electronics,4,36,Garciafort,mobile,51.241.30.149,"351 Frazier Radial Apt. 989\nPort Charles, OH ...","182 House Island Suite 198\nEast Scott, FM 84301",0,98,23
1472950,61.80,2024-01-12 16:21:32,bank transfer,electronics,5,34,Lake Josephberg,desktop,210.67.203.4,"27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...","27307 Gonzalez Shore Suite 661\nPort Lynn, WV ...",0,191,16
1472951,376.44,2024-02-19 18:57:20,bank transfer,clothing,5,34,Fullermouth,desktop,107.116.208.218,Unit 0520 Box 5911\nDPO AE 75554,Unit 0520 Box 5911\nDPO AE 75554,0,274,18

## **Gerando Insights**

In [19]:
#Contando o número de fraudes no total
numero_fraudes = df_dados['Is Fraudulent'].sum()
numero_fraudes

np.int64(73838)

In [20]:
#Fraudes e não fraudes
# 0 para fraude
# 1 para não foi fraude
fraude = df_dados['Is Fraudulent'].value_counts()
fraude

Is Fraudulent
0    1399114
1      73838
Name: count, dtype: int64

In [21]:
#Endereços de entrega que mais retornam 
endereco = df_dados['Shipping Address'].value_counts().head(10)
endereco

Shipping Address
USS Sanchez\nFPO AE 14652                                 2
USCGC Holmes\nFPO AA 56289                                2
USCGC Brown\nFPO AE 16210                                 2
USNV Black\nFPO AP 75390                                  2
634 May Keys\nPort Cherylview, NV 75063                   1
16282 Dana Falls Suite 790\nRothhaven, IL 15564           1
828 Strong Loaf Apt. 646\nNew Joshua, UT 84798            1
29799 Jason Hills Apt. 439\nWest Richardtown, OH 36093    1
192 Mark Ranch Apt. 531\nCookport, GU 65164               1
7108 Lang Forge\nPort Tricia, SC 02827                    1
Name: count, dtype: int64

In [35]:
#Mostra os dados apenas dos pedidos fraudulentos 
pedidos_fraudulentos = df_dados[df_dados['Is Fraudulent'] == 1].head(50)
pedidos_fraudulentos[['Is Fraudulent', 'Account Age Days', 'Transaction Hour', 'Transaction Date', 'Customer Age', 'Device Used', 'Product Category', 'Payment Method']]

,Is Fraudulent,Account Age Days,Transaction Hour,Transaction Date,Customer Age,Device Used,Product Category,Payment Method
32,1,147,13,2024-01-17 13:18:27,32,tablet,clothing,PayPal
68,1,65,1,2024-03-19 17:10:23,36,mobile,health & beauty,bank transfer
85,1,30,20,2024-01-10 20:08:38,37,desktop,home & garden,debit card
92,1,12,10,2024-01-06 10:28:06,30,tablet,clothing,credit card
191,1,9,17,2024-01-30 17:40:15,32,mobile,health & beauty,credit card
202,1,202,2,2024-01-03 20:26:20,31,mobile,electronics,bank transfer
221,1,218,11,2024-01-04 11:49:12,50,mobile,clothing,debit card
255,1,263,23,2024-01-10 23:20:37,36,mobile,home & garden,PayPal
262,1,266,1,2024-01-04 20:02:48,32,mobile,clothing,PayPal
267,1,325,1,2024-02-01 01:27:32,40,tablet,clothing,debit card
274,1,153,5,2024-03-26 06:53:29,58,desktop,clothing,debit card
287,1,144,2,2024-02-10 13:55:37,40,mobile,electronics,bank transfer
307,1,305,22,2024-02-05 22:22:03,38,tablet,clothing,debit card
319,1,254,15,2024-03-24 15:50:20,31,tablet,toys & games,debit card
325,1,4,2,2024-02-06 02:51:11,30,mobile,home & garden,bank transfer
331,1,210,14,2024-02-19 14:05:00,41,tablet,home & garden,credit card
350,1,105,2,2024-03-02 05:35:49,29,desktop,health & beauty,PayPal
357,1,27,3,2024-02-05 23:43:04,35,desktop,home & garden,bank transfer
414,1,29,20,2024-01-26 20:30:11,40,mobile,clothing,PayPal
443,1,23,13,2024-01-22 13:55:59,49,desktop,health & beauty,PayPal
454,1,362,5,2024-01-10 04:42:55,30,tablet,electronics,PayPal
484,1,163,5,2024-02-16 17:52:12,36,mobile,clothing,credit card
499,1,156,2,2024-02-10 02:22:52,48,tablet,health & beauty,debit card
539,1,64,0,2024-01-09 00:56:26,59,tablet,health & beauty,PayPal
544,1,38,0,2024-01-01 09:22:51,44,desktop,health & beauty,bank transfer
550,1,13,4,2024-01-10 06:10:26,51,desktop,home & garden,credit card
586,1,15,19,2024-02-04 19:32:28,29,mobile,clothing,credit card
594,1,243,11,2024-01-27 11:36:03,32,mobile,toys & games,PayPal
620,1,1,15,2024-02-07 15:02:15,41,tablet,health & beauty,bank transfer
655,1,336,2,2024-03-07 02:04:05,59,desktop,health & beauty,bank transfer
730,1,25,18,2024-03-28 18:52:23,38,desktop,electronics,debit card
762,1,253,20,2024-02-25 20:50:51,35,tablet,toys & games,bank transfer
818,1,277,18,2024-02-10 18:49:43,49,desktop,health & beauty,debit card
839,1,9,5,2024-03-09 16:24:58,28,mobile,clothing,bank transfer
878,1,294,15,2024-03-16 15:51:11,39,desktop,clothing,credit card
889,1,216,22,2024-03-03 22:58:58,57,desktop,clothing,credit card
895,1,27,4,2024-01-11 07:03:34,54,tablet,home & garden,debit card
906,1,9,18,2024-03-11 18:21:31,38,tablet,toys & games,debit card
919,1,213,1,2024-03-15 01:06:02,57,tablet,electronics,debit card
960,1,291,3,2024-01-07 03:06:51,24,mobile,clothing,debit card
962,1,14,3,2024-02-26 02:05:13,45,tablet,home & garden,PayPal
965,1,1,3,2024-02-07 03:35:21,41,mobile,toys & games,bank transfer
980,1,16,6,2024-03-28 06:22:21,41,desktop,home & garden,credit card
1035,1,20,10,2024-01-06 10:52:19,30,desktop,toys & games,credit card
1048,1,13,5,2024-03-10 04:21:17,49,desktop,electronics,debit card
1210,1,308,1,2024-03-18 01:26:59,44,desktop,home & garden,PayPal
1220,1,27,2,2024-03-24 00:38:53,41,mobile,clothing,PayPal
1261,1,6,1,2024-02-07 20:54:40,28,mobile,health & beauty,PayPal
1266,1,307,20,2024-02-20 20:09:10,39,tablet,toys & games,bank transfer
1286,1,28,3,2024-01-27 02:39:11,42,tablet,clothing,bank transfer

In [33]:
#Média do horário em que eram feitas as transações fraudulentas
media = pedidos_fraudulentos[['Transaction Hour']].mean()
media

Transaction Hour    8.76
dtype: float64

In [26]:
#Mostra a quantia por categoria nas colunas, nesta análise foi possível 
#visualizar que a maioria das transações foram feitas com cartão de crédito, na compra de vestuários.
quantia_categoria = pedidos_fraudulentos[['Payment Method', 'Product Category']].value_counts().reset_index(name='Count')
quantia_categoria

   Payment Method Product Category  Count
0     credit card         clothing      5
1      debit card         clothing      5
2          PayPal         clothing      4
3   bank transfer  health & beauty      4
4          PayPal  health & beauty      4
5     credit card    home & garden      3
6          PayPal    home & garden      3
7   bank transfer     toys & games      3
8      debit card      electronics      3
9      debit card    home & garden      2
10  bank transfer         clothing      2
11     debit card     toys & games      2
12  bank transfer    home & garden      2
13  bank transfer      electronics      2
14     debit card  health & beauty      2
15         PayPal      electronics      1
16         PayPal     toys & games      1
17    credit card     toys & games      1
18    credit card  health & beauty      1

In [27]:
#Verificando se os IP's utilizados nos pedidos fraudulentos se repetem, através dessa 
# análise é possível ver que não há recorrência de IP's
ip_fraudulentos = pedidos_fraudulentos['IP Address'].value_counts()
ip_fraudulentos

IP Address
78.50.82.205       1
65.77.31.204       1
211.189.218.190    1
213.226.163.230    1
54.172.17.233      1
129.176.195.216    1
148.64.174.255     1
6.216.2.252        1
29.104.189.18      1
125.72.131.119     1
64.99.216.14       1
117.102.32.216     1
100.158.28.175     1
166.133.224.120    1
108.128.142.186    1
165.53.241.164     1
36.127.153.114     1
53.34.55.45        1
12.250.243.91      1
24.60.43.191       1
142.73.216.218     1
220.128.222.195    1
126.22.145.28      1
6.10.73.106        1
1.31.134.13        1
39.88.248.2        1
37.237.226.67      1
84.74.234.241      1
113.140.46.6       1
29.154.12.141      1
79.219.193.6       1
11.246.246.234     1
124.195.247.137    1
189.70.148.180     1
131.34.42.100      1
140.77.76.91       1
109.36.33.18       1
92.19.237.162      1
110.238.70.53      1
28.130.76.26       1
112.115.93.209     1
117.70.93.131      1
57.22.208.167      1
194.132.87.233     1
132.72.69.236      1
190.145.169.240    1
141.205.136.7      1
104.112.126.241    1
37.145.205.73      1
222.239.252.76     1
Name: count, dtype: int64

In [32]:
#Ticket médio de $700.18 
ticket_medio_fraudado = pedidos_fraudulentos[pedidos_fraudulentos['Is Fraudulent'] == 1]['Transaction Amount'].mean()
ticket_medio_fraudado

np.float64(700.1812)

In [38]:
#Retornando apenas os pedidos não fraudulentos, para fazer uma comparação e tentar identificar anomalias. 
pedidos_nao_fraudulentos = df_dados[df_dados['Is Fraudulent'] == 0].head(50)
pedidos_nao_fraudulentos[['Payment Method', 'Product Category']]

   Payment Method Product Category
0   bank transfer      electronics
1      debit card      electronics
2          PayPal    home & garden
3   bank transfer         clothing
4   bank transfer         clothing
5   bank transfer     toys & games
6          PayPal     toys & games
7     credit card  health & beauty
8   bank transfer    home & garden
9   bank transfer  health & beauty
10         PayPal     toys & games
11         PayPal    home & garden
12    credit card    home & garden
13     debit card         clothing
14  bank transfer    home & garden
15     debit card    home & garden
16  bank transfer      electronics
17     debit card      electronics
18     debit card     toys & games
19         PayPal         clothing
20    credit card  health & beauty
21    credit card     toys & games
22     debit card     toys & games
23     debit card     toys & games
24  bank transfer         clothing
25  bank transfer  health & beauty
26  bank transfer     toys & games
27     debit card  health & beauty
28     debit card  health & beauty
29    credit card    home & garden
30     debit card      electronics
31    credit card  health & beauty
33     debit card         clothing
34     debit card    home & garden
35    credit card    home & garden
36    credit card      electronics
37  bank transfer         clothing
38         PayPal     toys & games
39  bank transfer    home & garden
40  bank transfer      electronics
41         PayPal    home & garden
42     debit card    home & garden
43     debit card         clothing
44    credit card      electronics
45     debit card      electronics
46         PayPal  health & beauty
47         PayPal     toys & games
48     debit card      electronics
49     debit card  health & beauty
50     debit card    home & garden

In [45]:
#Nos pedidos fraudulentos, a forma de pagamento que mais retorna é com cartão de crédito, 
#enquanto nos pedidos não fraudulentos, a maioria das transações são feitas com cartão de débito ou transferências bancárias. 
nf_recorrencia_produtos_pagamentos = pedidos_nao_fraudulentos[['Payment Method', 'Product Category']].value_counts()
nf_recorrencia_produtos_pagamentos

Payment Method  Product Category
debit card      electronics         5
PayPal          toys & games        4
debit card      home & garden       4
bank transfer   clothing            4
debit card      health & beauty     3
                clothing            3
bank transfer   home & garden       3
credit card     health & beauty     3
PayPal          home & garden       3
bank transfer   electronics         3
debit card      toys & games        3
credit card     home & garden       3
                electronics         2
bank transfer   toys & games        2
                health & beauty     2
PayPal          clothing            1
                health & beauty     1
credit card     toys & games        1
Name: count, dtype: int64